#- name: clone repo ansible 
#  git:
#     repo: 'https://boschpeter:Peter\!2020@github.com/boschpeter/ansible.git'
#     dest: /home/boscp08/Projects/scratch/virtual-insanity/ansible
#- name: clone repo socialcoin-api 
#  git:
#     repo: 'https://boschpeter:Peter\!2020@github.com/boschpeter/socialcoin-api.git'
#     dest: /home/boscp08/Projects/scratch/virtual-insanity/socialcoin-api
  
  #- name: Create APP Directory 
  #  file: path=/home/boscp08/Projects/scratch/virtual-insanity state=directory

  #- name: Copy Private Key
  #  copy: src={{privateKey}} dest={{homeDir}} mode=0600

  - name: Git Clone Repo
    git:  #repo=git@github.com:boschpeter:Peter\!2020/ansible.git dest=/home/boscp08/Projects/scratch/virtual-insanity  update=yes force=yes accept_hostkey=yes key_file=/home/boscp08/.ssh/id_rsa
      repo: 'https://{{ git_user }}:Peter\!2020@github.com/boschpeter/socialcoin-api.git'
      dest: /home/boscp08/Projects/scratch/virtual-insanity/socialcoin-api
      #register: git_finished

